# Generated by Django 5.0.2 on 2024-03-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signinform',
            old_name='ConfirmPassword',
            new_name='confirmpassword',
        ),
        migrations.AlterField(
            model_name='signinform',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
