# Generated by Django 5.0.2 on 2024-03-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_medicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SigninForm',
        ),
    ]
